name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Download ClashKit.xcframework.zip
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: Clash-for-Apple/clash-interface
          tag: ${{ github.event.inputs.version }}
          path: ./
          file: ClashKit.xcframework.zip
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
      - name: Caculate file checksum
        run: |
          export TEMP=`shasum -a 256 ./ClashKit.xcframework.zip`
          export CHECKSUM=${TEMP:0:64}
          echo "FILE_CHECKSUM=${CHECKSUM}" >> $GITHUB_ENV
          unset CHECKSUM
          unset TEMP

      - name: Update package file
        run: |
          echo "// swift-tools-version:5.5" > Package.swift
          echo "" >> Package.swift
          echo "import PackageDescription" >> Package.swift
          echo "" >> Package.swift
          echo "let package = Package(" >> Package.swift
          echo "  name: \"ClashKit\"," >> Package.swift
          echo "  products: [.library(name: \"ClashKit\", targets: [\"ClashKit\"])]," >> Package.swift
          echo "  targets: [.binaryTarget(name: \"ClashKit\", url: \"https://github.com/Clash-for-Apple/ClashKit/releases/download/${{ github.event.inputs.version }}/ClashKit.xcframework.zip\", checksum: \"${{ env.FILE_CHECKSUM }}\")]" >> Package.swift
          echo ")" >> Package.swift
          
      - name: Commit
        run: |
          git config --local user.email "release-bot@users.noreply.github.com"
          git config --local user.name "release-bot"
          git config remote.origin.url "https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Clash-for-Apple/ClashKit.git"
          git add ./Package.swift
          git commit -m "Release ${{ github.event.inputs.version }}!!!" -a
          git push origin main
          git tag -a ${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }}!!!"
          git push origin --tags
          
      - name: Upload ClashKit.xcframework.zip
        uses: softprops/action-gh-release@v1
        with: 
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          files: ./ClashKit.xcframework.zip
