name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string
      checksum:
        description: 'Zip file checksum'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update package file
        run: |
          echo "// swift-tools-version:5.5" > Package.swift
          echo "" >> Package.swift
          echo "import PackageDescription" >> Package.swift
          echo "" >> Package.swift
          echo "let package = Package(" >> Package.swift
          echo "  name: \"ClashKit\"," >> Package.swift
          echo "  products: [.library(name: \"ClashKit\", targets: [\"ClashKit\"])]," >> Package.swift
          echo "  targets: [.binaryTarget(name: \"ClashKit\", url: \"https://github.com/Clash-for-Apple/clash-interface/releases/download/${{ github.event.inputs.checksum }}/ClashKit.xcframework.zip\", checksum: \"${{ github.event.inputs.version }}\")]" >> Package.swift
          echo ")" >> Package.swift
          
      - name: Commit
        run: |
          git config --local user.email "release-bot@users.noreply.github.com"
          git config --local user.name "release-bot"
          git config remote.origin.url "https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Clash-for-Apple/ClashKit.git"
          git add ./Package.swift
          git commit -m "Release ${{ github.event.inputs.version }}!!!" -a
          git push origin main
          git tag -a ${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }}!!!"
          git push origin --tags
